#pragma once

using namespace ATL;

template <class T>
class CProxy_IATLWebSocketEvents : public IConnectionPointImpl<T, &__uuidof(_IATLWebSocketEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
